name: Release

on:
  push:
    branches: master
    paths:
      - 'packages/**'
      - '!packages/**/*.test.js'
      - '!packages/**/*.md'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          check-latest: true

      - name: Setup NPM
        env:
          NPM_REGISTRY: ${{ secrets.NPM_REGISTRY }}
        run: |
          echo "//registry.npmjs.org/:_authToken=$NPM_REGISTRY" > .npmrc

      - name: Install Yarn
        run: npm install --global yarn

      - name: Install dependencies
        run: yarn install --prefer-offline --frozen-lockfile

      - name: Build packages
        run: yarn build

      - name: Lint code
        run: yarn lint

      - name: Run unit tests
        run: yarn test

      - name: Setup Identity
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor}}@users.noreply.github.com"

      - name: Graduation
        continue-on-error: true
        id: graduation
        run: yarn lerna publish --include-merged-tags --conventional-graduate --yes
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Release
        if: ${{ steps.graduation.outcome == 'failure'  }}
        run: yarn lerna publish --yes
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
