name: Release

on:
  push:
    branches: master
    paths:
      - 'packages/**'
      - '!packages/**/*.test.js'
      - '!packages/**/*.md'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          check-latest: true

      - name: "Setup npm"
        run: |
          npm set @pedrobslisboa:registry=https://npm.pkg.github.com/pedrobslisboa
          npm set "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}"

      - name: Install Yarn
        run: npm install --global yarn

      - name: Install dependencies
        run: yarn install --prefer-offline --frozen-lockfile

      - name: Build packages
        run: yarn build

      - name: Lint code
        run: yarn lint

      - name: Run unit tests
        run: yarn test

      - name: Create release
        if: github.ref == 'refs/heads/master'
        run: yarn lerna publish --include-merged-tags --conventional-graduate --yes
      
      - name: Bump Prod Version Fallback
        if: ${{ always() && steps.graduateRelease.outcome == 'failure'  }}
        run: |
          echo Falling back to non-graduate release due to https://github.com/lerna/lerna/issues/2532
          git stash
          yarn lerna version --conventional-commits --yes